### ISSUE TITLE
1.20.6

### ISSUE THREAD

**Issue by PukPukov** [NimajnebEC/auto-elytra#17]
When trying to fly on 1.20.6, game crashes with that error:

```
net.minecraft.class_148: Ticking entity
	at net.minecraft.class_1937.method_18472(class_1937.java:499) ~[client-intermediary.jar:?]
	at net.minecraft.class_638.method_32124(class_638.java:261) ~[client-intermediary.jar:?]
	at net.minecraft.class_5574.method_31791(class_5574.java:54) ~[client-intermediary.jar:?]
	at net.minecraft.class_638.method_18116(class_638.java:257) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:2007) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1281) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:888) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:265) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) [fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.15.10.jar:?]
Caused by: java.lang.NoSuchFieldError: Class net.minecraft.class_1294 does not have member field 'net.minecraft.class_1291 field_5902'
	at net.minecraft.class_746.autoelytra$canStartFlying(class_746.java:1881) ~[client-intermediary.jar:?]
	at net.minecraft.class_746.handler$zdp000$autoelytra$tryEquipElytra(class_746.java:1861) ~[client-intermediary.jar:?]
	at net.minecraft.class_746.method_6007(class_746.java:786) ~[client-intermediary.jar:?]
	at net.minecraft.class_1309.method_5773(class_1309.java:2529) ~[client-intermediary.jar:?]
	at net.minecraft.class_1657.method_5773(class_1657.java:306) ~[client-intermediary.jar:?]
	at net.minecraft.class_742.method_5773(class_742.java:59) ~[client-intermediary.jar:?]
	at net.minecraft.class_746.method_5773(class_746.java:220) ~[client-intermediary.jar:?]
	at net.minecraft.class_638.method_18646(class_638.java:1658) ~[client-intermediary.jar:?]
	at net.minecraft.class_1937.method_18472(class_1937.java:492) ~[client-intermediary.jar:?]
	... 10 more
```

**Comment by MrTacoDestroyer** [comment]
I have the same issue on Fabric. Despite it saying It's compatible with every version of 1.20, It crashes on 1.20.6 when trying to use it.

**Comment by PukPukov** [comment]
Superseeded by #18.
